name: Auto Grading

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: List Files in Repository
      run: ls -R

    - name: Debug - Display solution.txt Content
      run: |
        if [ -f "solution.txt" ]; then
          echo "📄 Content of solution.txt:"
          cat solution.txt
        else
          echo "❌ solution.txt file not found!"
          exit 1
        fi

    - name: Debug - Display Expected Answers
      run: |
        echo "📊 Expected Answers:"
        echo $EXPECTED_ANSWERS | jq -r '.[]'

    - name: Validate Solution
      env:
        EXPECTED_ANSWERS: ${{ secrets.EXPECTED_ANSWERS }}
      run: |
        if [ ! -f "solution.txt" ]; then
          echo "❌ Missing solution.txt in the root directory!"
          exit 1
        fi

        # Read expected answers from secret
        expected_answers=$(echo $EXPECTED_ANSWERS | jq -r '.[]')

        # Read answers from solution.txt
        IFS=$'\n' read -d '' -r -a answers < solution.txt

        # Validate answers
        index=0
        for expected_answer in $expected_answers; do
          if [[ "${answers[$index]}" != *"$expected_answer"* ]]; then
            echo "❌ Incorrect answer for question $((index+1))!"
            echo "Expected: $expected_answer"
            echo "Found: ${answers[$index]}"
            exit 1
          fi
          index=$((index+1))
        done

        echo "✅ All answers are correct!"
